from password_gen import generate_password
from tkinter import *
from tkinter import ttk

root = Tk()
root.geometry("600x400")
root.title("Password Generator")
root.resizable(False, False)
frame = Frame(
        root,
        # width=300,
        # height=200,
        bg="#2B2D42"
)

def create_gui():

    # The password as generated by password_gen.py
    pw = generate_password()

    def copy_to_clipboard():
        root.clipboard_clear()
        root.clipboard_append(password_label['text'])
    
    def regenerate_pass():
        new_pw = generate_password()
        # password_label = ttk.Label(root, text=pw)
        password_label.config(text=new_pw)
    
    frame.place(relwidth=1, relheight=1)

    frame_label = Label (
        frame,
        text="Generate a password",
        bg="#2B2D42",
        fg="#FFFFFF",
        font=("Arial", 24, "bold")
    )
    frame_label.place(x=50, y=50)

    password_label = Label(
        frame, 
        text=pw,
        bg="#2B2D42",
        fg="#F8F32B",
        font=("Arial", 24, "bold"),
        )
    password_label.place(x=50, y=100)
    
    copy_button = Button(
        frame,
        text="Copy", 
        command=copy_to_clipboard, 
        highlightthickness=0,
        bg="#8D99AE",
        fg="#000000",
        font=("Arial", 12, "bold"),
        activebackground="#667080",
        activeforeground="#000000",
        borderwidth=0,
        width=12,
        height=2
        )
    copy_button.place(x=250, y=200)
    
    quit_button = Button(
        frame, 
        text="Quit", 
        command=root.destroy,
        highlightthickness=0,
        bg="#8D99AE",
        fg="#000000",
        font=("Arial", 12, "bold"),
        activebackground="#667080",
        activeforeground="#000000",
        borderwidth=0,
        width=12,
        height=2
        )
    quit_button.place(x=400, y=200)

    regenerate_button = Button(
        frame, 
        text="Regenerate", 
        command=regenerate_pass,
        highlightthickness=0,
        bg="#FFFFFF",
        fg="#000000",
        font=("Arial", 12, "bold"),
        activebackground="#F8F32B",
        activeforeground="#000000",
        borderwidth=0,
        width=12,
        height=2
        )
    regenerate_button.place(x=50, y=200)

    root.mainloop()